langchain4j:
    open-ai:
        chat-model:
            api-key: 123456
            log-requests: true
            log-responses: true
            model-name: random
            temperature: 0.7
            base-url: http://127.0.0.1:9090/v1
spring:
    application:
        name: Langchain
